https://stackoverflow.com/questions/51851733/tensorflow-dataset-sliding-window-batch-not-working


In [10]:
import tensorflow as tf
import numpy as np
dataset = tf.data.Dataset.from_tensor_slices(np.arange(100).reshape(20,2))
dataset = dataset.apply(tf.contrib.data.sliding_window_batch(window_size=4))
iterator = dataset.make_one_shot_iterator()
element = iterator.get_next()

with tf.Session() as sess:
    while True:
        try:
            print(sess.run(element))
        except tf.errors.OutOfRangeError:
            print('end')
            break

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[2 3]
 [4 5]
 [6 7]
 [8 9]]
[[ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[[ 6  7]
 [ 8  9]
 [10 11]
 [12 13]]
[[ 8  9]
 [10 11]
 [12 13]
 [14 15]]
[[10 11]
 [12 13]
 [14 15]
 [16 17]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]]
[[14 15]
 [16 17]
 [18 19]
 [20 21]]
[[16 17]
 [18 19]
 [20 21]
 [22 23]]
[[18 19]
 [20 21]
 [22 23]
 [24 25]]
[[20 21]
 [22 23]
 [24 25]
 [26 27]]
[[22 23]
 [24 25]
 [26 27]
 [28 29]]
[[24 25]
 [26 27]
 [28 29]
 [30 31]]
[[26 27]
 [28 29]
 [30 31]
 [32 33]]
[[28 29]
 [30 31]
 [32 33]
 [34 35]]
[[30 31]
 [32 33]
 [34 35]
 [36 37]]
[[32 33]
 [34 35]
 [36 37]
 [38 39]]
[[34 35]
 [36 37]
 [38 39]
 [40 41]]
[[36 37]
 [38 39]
 [40 41]
 [42 43]]
[[38 39]
 [40 41]
 [42 43]
 [44 45]]
[[40 41]
 [42 43]
 [44 45]
 [46 47]]
[[42 43]
 [44 45]
 [46 47]
 [48 49]]
[[44 45]
 [46 47]
 [48 49]
 [50 51]]
[[46 47]
 [48 49]
 [50 51]
 [52 53]]
[[48 49]
 [50 51]
 [52 53]
 [54 55]]
[[50 51]
 [52 53]
 [54 55]
 [56 57]]
[[52 53]
 [54 55]
 [56 57]
 [58 59]]
[[54 55]
 [56 57]

In [5]:
list(np.arange(30).reshape(3,10))

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
 array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])]